[package]
name = "archive"
version = "0.1.0"
authors = ["snsvrno <snsvrno@tuta.io>"]

[dependencies]
zip = "0.3.0"
ansi_term = "0.10.2"

output = { git = "https://github.com/Snsvrno/output-lp-rs", tag = "0.1.0" }